### ISSUE TITLE
Easy to customize

### ISSUE THREAD

**Issue by Kikobeats** [tachyons-css/tachyons-sass#9]
I don't know if this repository is auto-generated, but, ideally, I want rewrite it to extract style varaibles into a `_variables.scss` file. 

Very similar how boostrap do that, check it: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L95.

But using the tachyons-custom values: https://github.com/tachyons-css/tachyons-custom#src_variablescss.

Defining the values as default, it makes easy default new values by the user.

What do you think?

**Comment by dfosco** [comment]
@Kikobeats You can already do this if you just change the values of the current colors in `_colors.scss`. You'll have to stick to the same class names, but it's customizable enough.

To generate new classes, I've created a map with the colors provided in `_colors.scss` and then updated `_skins.scss` with a loop like this:

```scss

/* http://www.sassmeister.com/gist/49c70fc294789d9c5798a3cdc8103f4b */

/* _color-map.scss */
  $color-map: (
  "black": unquote("#{$black}"),
  "blue": unquote("#{$blue}")
);

/* _skins.scss */
@each $color-name, $color-prefix in $color-map {
 $color-value: nth($color-prefix, 1);

// Color classes
 .#{$color-name} {
   color: $color-value;
 }

 // Background Color classes
 .bg-#{$color-name} {
   background-color: $color-value;
 }
}
```

It then regenerates all color classes based on the variables passed to the map. I don't enjoy using Sass “magic tricks” as it can get out of hand _pretty fast_ – hard to read and bloated output – but this much felt ok. 

Creating new classes by hand is not exactly hard, but I don't see why we shouldn't automate it whenever it makes sense for customization & maintenance as long as it doesn't add too much complexity.

@mrmrs @johnotander thoughts on this? I could open a PR if you folks think it makes sense for the project.
